#!/bin/bash

# Full template deployment pipeline
# Usage: ./full-deployment.sh --template="habit-tracker" --price="45"

set -e

TEMPLATE_NAME=""
PRICE="45"
PLATFORMS="gumroad"
SOCIAL="twitter,linkedin"
AUTO_PUBLISH="false"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --template=*)
            TEMPLATE_NAME="${1#*=}"
            shift
            ;;
        --price=*)
            PRICE="${1#*=}"
            shift
            ;;
        --platforms=*)
            PLATFORMS="${1#*=}"
            shift
            ;;
        --social=*)
            SOCIAL="${1#*=}"
            shift
            ;;
        --auto-publish)
            AUTO_PUBLISH="true"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "$TEMPLATE_NAME" ]; then
    echo "❌ Template name is required. Use --template=name"
    exit 1
fi

echo "🚀 Starting full deployment for: $TEMPLATE_NAME"
echo "💰 Price: \$$PRICE"
echo "🏪 Platforms: $PLATFORMS"
echo "📱 Social: $SOCIAL"

# Step 1: Deploy to Gumroad
if [[ $PLATFORMS == *"gumroad"* ]]; then
    echo "📦 Deploying to Gumroad..."
    node automation-scripts/gumroad-deploy.js \
        --template="$TEMPLATE_NAME" \
        --price="$PRICE" \
        --publish="$AUTO_PUBLISH"
fi

# Step 2: Social media blast
echo "📱 Starting social media blast..."
node automation-scripts/social-blast.js \
    --template="$TEMPLATE_NAME" \
    --platforms="$SOCIAL" \
    --price="$PRICE"

# Step 3: Generate deployment report
echo "📊 Generating deployment report..."
cat > "deployment-report-$(date +%Y%m%d-%H%M%S).md" << REPORT
# Deployment Report: $TEMPLATE_NAME

**Date:** $(date)
**Template:** $TEMPLATE_NAME
**Price:** \$$PRICE
**Platforms:** $PLATFORMS
**Social Media:** $SOCIAL

## Next Steps:
1. ✅ Monitor Gumroad analytics
2. ✅ Track social media engagement
3. ✅ Respond to customer inquiries
4. ✅ Plan follow-up marketing
5. ✅ Collect customer feedback

## Success Metrics to Track:
- Sales within 24 hours: Target 1-2
- Social media engagement: Target 50+ interactions
- Repository stars: Target 10+
- Website traffic: Track via analytics

Generated by Micro-SaaS Automation Pipeline
REPORT

echo "🎉 Deployment complete! Check deployment report for next steps."
